import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import ChartBlock from "../components/ChartBlock";
import TotalCount from "../components/TotalCount";
import styles from "../styles/Home.module.css";
import { formatDate } from "../util";

const Wrapper = styled.div`
  width: 100%;
  height: max-content;

  @media (min-width: 30rem) {
    width: 31.25rem;
  }
`;

export default function Home({ days }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Wrapper>
          <TotalCount days={days} />
          <ChartBlock days={days} />
        </Wrapper>
      </main>

      <footer className={styles.footer}>
        <p>2022 &copy; Seungsoo Choi. All right reserved.</p>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getStaticProps() {
  const API_KEY = process.env.NEXT_PUBLIC_API_KEY;
  const API_URL = process.env.NEXT_PUBLIC_API_URL;
  const pageNo = 1;
  const numOfRows = 10;
  const startCreateDt = 20200101;
  const endCreateDt = formatDate(new Date());
  const url = `${API_URL}?ServiceKey=${API_KEY}&pageNo=${pageNo}&numOfRows=${numOfRows}&startCreateDt=${startCreateDt}&endCreateDt=${endCreateDt}`;

  const covidData = await fetch(
    url,
    {
      headers: {
        Accept: "application/json", // unexpected token < in json at position 0
      },
    },
    { method: "GET" }
  );
  const days = await covidData.json();

  return {
    props: {
      days,
    },
  };
}
