import Head from "next/head";
import Image from "next/image";
import ChartBlock from "../components/ChartBlock";
import styles from "../styles/Home.module.css";

export async function getStaticProps() {
  // Get external data from the file system, API, DB, etc.
  const API_KEY = process.env.API_KEY;
  const pageNo = 1;
  const numOfRows = 10;
  const startCreateDt = 20210217;
  const endCreateDt = 20220217;
  const url = `${process.env.NEXT_PUBLIC_API_URL}?ServiceKey=${API_KEY}&pageNo=${pageNo}&numOfRows=${numOfRows}&startCreateDt=${startCreateDt}&endCreateDt=${endCreateDt}`;

  const data = await fetch(
    url,
    {
      // 이부분이 어떤 도움을 준 것인지 알아봐야함.. 너무 고맙
      headers: {
        Accept: "application/json",
      },
    },
    { method: "GET" }
  ).then((response) => response.json());

  // The value of the `props` key will be
  //  passed to the `Home` component
  return {
    props: {
      data,
    },
  };
}

export default function Home({ data }) {
  const {
    response: { body },
  } = data;
  return body ? (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ChartBlock data={body.items.item} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  ) : (
    "loading.."
  );
}
